import localFont from "next/font/local";
import "./globals.css";
import Nav from "../components/Nav"; // Ensure correct path, single slash
import Intro from "../components/intro";
import dynamic from "next/dynamic";
import Projects from "@/components/projects";
import Contact from "@/components/contact";

const About = dynamic(() => import("../components/about"), {
  ssr: false, // This ensures the component is only rendered on the client side
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "My Portfolio",
  description: "Generated by Ahmad",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>{/* Meta and other head elements go here */}</head>
      <body>
        <Nav />
        {children}
        <Intro />
        <About />
        <Projects />
        <Contact />
      </body>
    </html>
  );
}
